const { _electron: electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'halo-organize-'));
const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => key !== 'ELECTRON_RUN_AS_NODE'));
const saved = page => page.waitForFunction(() => document.querySelector('#save-state').dataset.state === 'saved');
const disk = () => JSON.parse(fs.readFileSync(path.join(profile, 'settings.json'), 'utf8'));
(async () => {
  const packaged = process.argv.includes('--packaged');
  const app = await electron.launch({ executablePath: packaged ? path.join(root, 'release/win-unpacked/HALO MENU.exe') : require('electron'), args: [...(packaged ? [] : [root]), '--test-mode', '--aptic-profile=' + profile], env });
  try {
    await app.firstWindow(); const page = app.windows().find(w => w.url().endsWith('/index.html'));
    await page.waitForSelector('.row'); const errors = []; page.on('pageerror', e => errors.push(e.message));
    assert.equal(await page.locator('.row').count(), 12);
    await page.locator('#fold-groups').click(); assert.equal(await page.locator('.row').count(), 8);
    await page.keyboard.press('Control+f'); assert.equal(await page.locator('#action-search').evaluate(el => el === document.activeElement), true);
    await page.locator('#action-search').fill('copiar');
    assert.deepEqual(await page.locator('.row').evaluateAll(rows => rows.map(r => r.dataset.id)), ['edit', 'copy']);
    await page.keyboard.press('Escape'); assert.equal(await page.locator('.row').count(), 8, 'Search temporarily reveals collapsed descendants');
    await page.locator('#action-search').fill('imagenes'); assert.equal(await page.locator('.row').count(), 1);
    await page.locator('#action-search').fill('nada-coincide'); assert.equal(await page.locator('.list-empty').count(), 1);
    await page.keyboard.press('Escape'); await page.locator('#fold-groups').click();
    await page.locator('.row[data-id="edit"] .group-fold').click(); assert.equal(await page.locator('.row').count(), 8);
    await page.locator('.row[data-id="edit"] .group-fold').press('Enter'); assert.equal(await page.locator('.row').count(), 12);
    await page.locator('#select-many').click();
    await page.locator('.row[data-id="files"]').click(); await page.locator('.row[data-id="pictures"]').click();
    assert.equal(await page.locator('#batch-inspector').isVisible(), true);
    assert.equal(await page.locator('#inspector').isVisible(), false);
    assert.equal(await page.locator('#stage .batch-checked').count(), 2);
    await page.locator('#batch-color').fill('#123abc'); await page.locator('#batch-apply-color').click(); await saved(page);
    assert.equal(disk().items.find(i => i.id === 'files').color, '#123abc'); assert.equal(disk().items.find(i => i.id === 'pictures').color, '#123abc');
    await page.locator('#batch-group').click(); await saved(page);
    const group = disk().items[0]; assert.deepEqual(group.items.map(i => i.id), ['files', 'pictures']);
    assert.equal(await page.locator('#action-name').evaluate(el => el === document.activeElement), true);
    await page.locator('#undo').click(); await saved(page);
    assert.equal(disk().items.length, 8);
    // Ctrl-click starts batch mode, including selecting through the preview.
    await page.locator('.row[data-id="files"]').click({ modifiers: ['Control'] });
    await page.locator('#stage [data-id="pictures"]').click();
    await page.locator('#batch-duplicate').click(); await saved(page);
    assert.equal(disk().items.length, 10); assert.equal(await page.locator('#batch-names li').count(), 2);
    await page.locator('#undo').click(); await saved(page); assert.equal(disk().items.length, 8);
    await page.locator('#select-many').click(); await page.locator('#batch-all').click();
    const before = disk(); await page.locator('#batch-library').click();
    assert.match(await page.locator('#batch-error').innerText(), /dos acciones/); assert.deepEqual(disk(), before);
    await page.locator('#batch-none').click(); await page.locator('.row[data-id="downloads"]').click(); await page.locator('.row[data-id="pictures"]').click();
    await page.locator('#batch-library').click(); await saved(page);
    assert.deepEqual(disk().library.slice(-2).map(i => i.id), ['downloads', 'pictures']);
    await page.locator('#undo').click(); await saved(page);
    await page.locator('#select-many').click(); await page.locator('.row[data-id="files"]').click(); await page.locator('.row[data-id="downloads"]').click();
    await page.screenshot({ path: path.join(root, 'artifacts/organize-selection.png') });
    await page.locator('#batch-done').click();
    await page.locator('#action-search').fill('copiar'); await page.screenshot({ path: path.join(root, 'artifacts/organize-search.png') });
    assert.deepEqual(errors, []);
    console.log('PASS: search, accents, fold/unfold, keyboard search, batch selection via list/ring, group/color/copy/library, limits and undo');
  } finally { await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
