const { _electron: electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'halo-studio-'));
const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => key !== 'ELECTRON_RUN_AS_NODE'));
const saved = page => page.waitForFunction(() => document.querySelector('#save-state').dataset.state === 'saved');
const disk = () => JSON.parse(fs.readFileSync(path.join(profile, 'settings.json'), 'utf8'));
(async () => {
  const packaged = process.argv.includes('--packaged');
  const app = await electron.launch({ executablePath: packaged ? path.join(root, 'release/win-unpacked/HALO MENU.exe') : require('electron'), args: [...(packaged ? [] : [root]), '--test-mode', '--aptic-profile=' + profile], env });
  try {
    await app.firstWindow();
    const page = app.windows().find(w => w.url().endsWith('/index.html'));
    await page.waitForSelector('.row');
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.waitForTimeout(900);
    const before = await page.locator('#stage').boundingBox();
    await page.locator('#inspector').hover(); await page.mouse.wheel(0, 1300);
    await page.waitForTimeout(200);
    assert.deepEqual(await page.locator('#stage').boundingBox(), before, 'Inspector scroll leaves stage fixed');
    assert.equal(await page.locator('#scroll').evaluate(el => el.scrollTop), 0);
    await page.evaluate(() => { window.originalRing = document.querySelector('#stage .ring'); });
    await page.locator('.row[data-id="downloads"]').click();
    assert.equal(await page.evaluate(() => window.originalRing === document.querySelector('#stage .ring')), true, 'Selection retains radial DOM');
    // A real pointer drag must exchange both actions without removing either.
    await page.locator('#stage [data-id="files"]').dragTo(page.locator('#stage [data-id="downloads"]'));
    await saved(page);
    assert.deepEqual(disk().items.slice(0, 2).map(i => i.id), ['downloads', 'files']);
    await page.locator('#undo').click(); await saved(page);
    // Real pointer drags (the editor no longer uses native HTML5 drag and drop).
    const mouseDrag = async (from, to, { alt = false } = {}) => {
      await page.mouse.move(from.x, from.y); await page.mouse.down();
      await page.mouse.move(from.x + 6, from.y + 6, { steps: 2 });
      if (alt) await page.keyboard.down('Alt');
      await page.mouse.move(to.x, to.y, { steps: 10 }); await page.waitForTimeout(80);
      const feedback = await page.evaluate(() => ({ hint: document.querySelector('#stage').dataset.dropHint || '', marker: !!document.querySelector('#stage .ring-gap') }));
      await page.mouse.up(); if (alt) await page.keyboard.up('Alt');
      await page.waitForTimeout(320); return feedback;
    };
    // Positions are read once every glide has finished, as a person would aim.
    const still = () => page.waitForFunction(() => !document.getAnimations().some(a => a.playState === 'running' && !(a.effect?.getTiming().iterations === Infinity)));
    const centerOf = async selector => { await still(); return page.locator(selector).first().evaluate(el => { const r = el.getBoundingClientRect(); return { x: r.left + r.width / 2, y: r.top + r.height / 2 }; }); };
    const coordinateDrop = async (fromId, toId, altKey = false, edge = false) => {
      await still();
      const to = await page.evaluate(({ toId, edge }) => {
        const host = document.querySelector('#stage');
        const target = toId ? host.querySelector('[data-id="' + toId + '"]') : host, r = target.getBoundingClientRect();
        if (!toId) return { x: r.left + 5, y: r.top + 5 };
        const angle = parseFloat(target.style.getPropertyValue('--a')) * Math.PI / 180;
        const side = edge === 'before' ? -1 : edge === 'after' ? 1 : 0, delta = r.width / 2 + 5;
        const dx = side ? -Math.sin(angle) * delta * side : edge ? Math.cos(angle) * delta : 0;
        const dy = side ? Math.cos(angle) * delta * side : edge ? Math.sin(angle) * delta : 0;
        return { x: r.left + r.width / 2 + dx, y: r.top + r.height / 2 + dy };
      }, { toId, edge });
      return mouseDrag(await centerOf('#stage [data-id="' + fromId + '"]'), to, { alt: altKey });
    };
    const original = disk();
    await still(); const topCircle = await page.locator('#stage [data-id="files"]').boundingBox();
    await page.locator('#stage [data-id="pictures"]').dragTo(page.locator('#stage [data-id="files"]'), { targetPosition: { x: 2, y: topCircle.height / 2 } });
    await saved(page);
    assert.deepEqual(disk().items.map(i => i.id), ['pictures', ...original.items.map(i => i.id).filter(id => id !== 'pictures')], 'Real pointer drop beside a circle inserts before it');
    await page.locator('#undo').click(); await saved(page);
    // Each side inserts instead of exchanging: intervening actions shift intact.
    for (const [target, side] of [['files', 'before'], ['documents', 'after'], ['edit', 'before'], ['pictures', 'after']]) {
      const source = target === 'pictures' ? 'files' : 'pictures';
      const expected = original.items.map(i => i.id).filter(id => id !== source);
      expected.splice(expected.indexOf(target) + (side === 'after' ? 1 : 0), 0, source);
      const feedback = await coordinateDrop(source, target, false, side); await saved(page);
      assert.equal(feedback.marker, true, JSON.stringify({ target, side, feedback })); assert.match(feedback.hint, side === 'before' ? /Colocar antes/ : /Colocar después/);
      assert.deepEqual(disk().items.map(i => i.id), expected);
      assert.deepEqual(disk().library, original.library);
      await page.locator('#undo').click(); await saved(page);
    }
    // Rotated arcs use their own ordering, not the screen's left/right direction.
    await page.locator('[data-page="shape"]').click();
    await page.locator('[data-setting="rotation"]').evaluate(el => { el.value = '90'; el.dispatchEvent(new Event('input', { bubbles: true })); }); await saved(page);
    await page.locator('[data-page="actions"]').click(); await page.locator('.row[data-id="edit"]').click(); await page.waitForTimeout(600);
    const groupBefore = disk().items.find(i => i.id === 'edit').items.map(i => i.id);
    await coordinateDrop('copy', 'redo', false, 'after'); await saved(page);
    assert.deepEqual(disk().items.find(i => i.id === 'edit').items.map(i => i.id), [...groupBefore.slice(1), 'copy']);
    await page.locator('#undo').click(); await saved(page);
    await page.locator('#undo').click(); await saved(page);
    await coordinateDrop('pictures', 'desktop', false, true); await saved(page);
    assert.equal(disk().items.findIndex(i => i.id === 'pictures'), original.items.findIndex(i => i.id === 'desktop'));
    assert.equal(disk().items.findIndex(i => i.id === 'desktop'), original.items.findIndex(i => i.id === 'pictures'));
    assert.deepEqual(disk().library, original.library);
    await page.locator('#undo').click(); await saved(page);
    await coordinateDrop('pictures', null);
    assert.deepEqual((await page.evaluate(() => window.aptic.state())).config, original, 'Empty preview does not remove anything');
    await coordinateDrop('pictures', 'desktop', true); await saved(page);
    const created = disk().items.find(i => i.type === 'group' && i.items.some(k => k.id === 'pictures'));
    assert.deepEqual(created.items.map(i => i.id), ['desktop', 'pictures']);
    await page.locator('#undo').click(); await saved(page);
    await coordinateDrop('pictures', 'edit'); await saved(page);
    assert.ok(disk().items.find(i => i.id === 'edit').items.some(i => i.id === 'pictures'));
    await page.locator('#undo').click(); await saved(page);
    const drag = async (from, to) => mouseDrag(await centerOf(from), await centerOf(to));
    await drag('#stage [data-id="downloads"]', '#ring-store'); await saved(page);
    assert.ok(disk().library.some(i => i.id === 'downloads'));
    assert.ok(!disk().items.some(i => i.id === 'downloads'));
    await page.locator('#library-toggle').click();
    await page.locator('#library-search').fill('descargas');
    assert.equal(await page.locator('#library .tile').count(), 1);
    await page.locator('#library .tile').dblclick(); await saved(page);
    assert.ok(disk().items.some(i => i.id === 'downloads'), 'Double click actually inserts library action');
    await page.locator('#library-search').fill('');
    await page.locator('#library-catalog').click(); await page.locator('#library-search').fill('guardar');
    await page.locator('#library .tile').click(); await saved(page);
    assert.ok(disk().items.some(i => i.target === 'CommandOrControl+S'));
    await page.locator('#library-close').click();
    await drag('#stage [data-id="pictures"]', '#stage [data-id="edit"]'); await saved(page);
    assert.ok(disk().items.find(i => i.id === 'edit').items.some(i => i.id === 'pictures'));
    await page.locator('#undo').click(); await saved(page);
    assert.ok(disk().items.some(i => i.id === 'pictures'));
    await page.locator('[data-page="appearance"]').click(); await page.evaluate(() => document.querySelectorAll('details.more-settings').forEach(d => { d.open = true; })); await page.locator('[data-palette="lagoon"]').click(); await saved(page);
    assert.equal(disk().ringAccent, '#4cc0bd'); assert.equal(disk().theme, 'carbon');
    assert.equal(await page.locator('#page-appearance .ring').evaluate(el => getComputedStyle(el).getPropertyValue('--accent').trim()), '#4cc0bd');
    await page.locator('[data-page="shortcut"]').click();
    await page.evaluate(() => document.querySelectorAll('details.more-settings').forEach(d => { d.open = true; }));
    await page.locator('[data-setting="mouseMode"] [data-value="double"]').click();
    await page.locator('[data-setting="selectionMode"] [data-value="precise"]').click();
    await page.locator('[data-setting="wheelNavigation"]').check(); await saved(page);
    assert.equal(disk().mouseMode, 'double'); assert.equal(disk().selectionMode, 'precise'); assert.equal(disk().wheelNavigation, true);
    // Exercise radial hit testing and dwell lifecycle without executing desktop actions.
    const radial = await page.evaluate(async () => {
      const { mountRadial } = await import('./radial.js');
      const { config } = await window.aptic.state();
      const host = document.createElement('div'); host.style.cssText = 'position:fixed;left:0;top:0;width:600px;height:600px;z-index:100'; document.body.append(host);
      const c = { ...config, nativeIcons: false, animation: 'none', duration: 0, items: config.items.slice(0, 2), selectionMode: 'precise' };
      let choices = 0;
      let api = mountRadial(host, c, { mode: 'live', instant: true, onChoose: () => choices++ });
      const rect = api.root.getBoundingClientRect();
      api.track(rect.left, rect.top - 50); const gap = api.aimedItem;
      api.track(rect.left, rect.top - globalThis.apticGeometry.ring(c).radius); const hit = api.aimedItem?.id;
      api.destroy();
      api = mountRadial(host, { ...c, selectionMode: 'dwell', dwellDelay: 350 }, { mode: 'live', instant: true, onChoose: () => choices++ });
      api.aimAt(0); await new Promise(r => setTimeout(r, 400)); const dwell = choices;
      api.aimAt(1); api.destroy(); await new Promise(r => setTimeout(r, 400));
      const cancelled = choices === dwell;
      api = mountRadial(host, { ...c, selectionMode: 'sector' }, { mode: 'live', instant: true, hold: true, onChoose: () => choices++ });
      const center = api.root.getBoundingClientRect(); api.track(center.left, center.top); api.queueTrack(center.left, center.top - 90); api.release();
      const released = choices === dwell + 1;
      api.destroy(); host.remove(); return { gap, hit, dwell, cancelled, released };
    });
    assert.equal(radial.gap, null); assert.ok(radial.hit); assert.equal(radial.dwell, 1); assert.equal(radial.cancelled, true); assert.equal(radial.released, true);
    await page.locator('[data-page="actions"]').click();
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')).setSize(1080, 700));
    await page.waitForTimeout(500);
    const fits = await page.evaluate(() => ['.studio', '#stage', '#inspector', '#ring-store'].every(s => { const r = document.querySelector(s).getBoundingClientRect(); return r.width > 100 && r.bottom <= innerHeight && r.right <= innerWidth; }));
    assert.equal(fits, true, 'Workspace fits minimum window size');
    await page.screenshot({ path: path.join(root, 'artifacts/studio-compact.png') });
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')).setSize(1440, 900));
    await page.waitForTimeout(500);
    await page.locator('#inspector').evaluate(el => el.scrollTop = 0);
    await page.screenshot({ path: path.join(root, 'artifacts/studio-updated.png') });
    await page.locator('#library-toggle').click(); await page.locator('#library-search').fill('');
    await page.screenshot({ path: path.join(root, 'artifacts/library-updated.png') });
    // Adding asks what first; a new web names itself after its site until it is renamed.
    if (await page.locator('#library-card').isVisible()) await page.locator('#library-close').click();
    await page.locator('.row[data-id="files"]').click();
    await page.locator('#add').click(); await page.locator('#add-dialog [data-add="url"]').click();
    await page.locator('#action-url').fill('https://www.github.com/halo'); await saved(page);
    assert.ok(disk().items.some(i => i.type === 'url' && i.label === 'Github' && i.target === 'https://www.github.com/halo'), 'New web is named after its site');
    await page.keyboard.press('Control+n'); await page.locator('#add-query').fill('captura'); await page.locator('#add-recipes .add-recipe').first().click(); await saved(page);
    assert.ok(disk().items.some(i => i.label === 'Captura de pantalla'), 'Prepared action is added from the dialog');
    // Inspector: a note and a hidden action never reach the real ring, but stay in the editor.
    await page.locator('#library-close').click().catch(() => {});
    await page.locator('.row[data-id="documents"]').click();
    await page.locator('#insp-more').evaluate(d => { d.open = true; });
    await page.locator('#action-note').fill('Mis papeles'); await page.locator('#toggle-visible').click(); await saved(page);
    assert.equal(disk().items.find(i => i.id === 'documents').hidden, true); assert.equal(disk().items.find(i => i.id === 'documents').note, 'Mis papeles');
    assert.equal(await page.locator('.row[data-id="documents"].is-hidden').count(), 1);
    await page.evaluate(() => window.aptic.showMenu());
    const overlay = app.windows().find(w => w.url().endsWith('/overlay.html'));
    await overlay.waitForSelector('.ring[data-open] .ring-opt', { state: 'attached' });
    assert.equal(await overlay.locator('.ring-opt[data-id="documents"]').count(), 0, 'Hidden action stays out of the ring');
    await overlay.keyboard.press('Escape'); await page.waitForTimeout(400);
    await page.locator('#action-visible').check(); await saved(page);
    assert.equal('hidden' in disk().items.find(i => i.id === 'documents'), false);
    assert.deepEqual(errors, []);
    console.log('PASS: hidden actions and notes, fixed panels, radial DOM reuse, circle drag, library search/double click/catalog, groups/undo, custom palette, gesture persistence, precise/dwell/release, minimum window layout');
  } finally { await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
