const { _electron: electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'halo-studio-'));
const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => key !== 'ELECTRON_RUN_AS_NODE'));
const saved = page => page.waitForFunction(() => document.querySelector('#save-state').dataset.state === 'saved');
const disk = () => JSON.parse(fs.readFileSync(path.join(profile, 'settings.json'), 'utf8'));
(async () => {
  const packaged = process.argv.includes('--packaged');
  const app = await electron.launch({ executablePath: packaged ? path.join(root, 'release/win-unpacked/HALO MENU.exe') : require('electron'), args: [...(packaged ? [] : [root]), '--test-mode', '--aptic-profile=' + profile], env });
  try {
    await app.firstWindow();
    const page = app.windows().find(w => w.url().endsWith('/index.html'));
    await page.waitForSelector('.row');
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.waitForTimeout(900);
    const before = await page.locator('#stage').boundingBox();
    await page.locator('#inspector').hover(); await page.mouse.wheel(0, 1300);
    await page.waitForTimeout(200);
    assert.deepEqual(await page.locator('#stage').boundingBox(), before, 'Inspector scroll leaves stage fixed');
    assert.equal(await page.locator('#scroll').evaluate(el => el.scrollTop), 0);
    await page.evaluate(() => { window.originalRing = document.querySelector('#stage .ring'); });
    await page.locator('.row[data-id="downloads"]').click();
    assert.equal(await page.evaluate(() => window.originalRing === document.querySelector('#stage .ring')), true, 'Selection retains radial DOM');
    // A real pointer drag must exchange both actions without removing either.
    await page.locator('#stage [data-id="files"]').dragTo(page.locator('#stage [data-id="downloads"]'));
    await saved(page);
    assert.deepEqual(disk().items.slice(0, 2).map(i => i.id), ['downloads', 'files']);
    await page.locator('#undo').click(); await saved(page);
    // At the edge of scaled circles Chromium may target the stage, not the button.
    const coordinateDrop = (fromId, toId, altKey = false, edge = false) => page.evaluate(({ fromId, toId, altKey, edge }) => {
      const host = document.querySelector('#stage'), src = host.querySelector('[data-id="' + fromId + '"]'), dt = new DataTransfer();
      src.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer: dt }));
      const target = toId ? host.querySelector('[data-id="' + toId + '"]') : host, r = target.getBoundingClientRect();
      const angle = parseFloat(target.style.getPropertyValue('--a')) * Math.PI / 180;
      const side = edge === 'before' ? -1 : edge === 'after' ? 1 : 0;
      const delta = r.width / 2 + 5;
      const dx = side ? -Math.sin(angle) * delta * side : edge ? Math.cos(angle) * delta : 0;
      const dy = side ? Math.cos(angle) * delta * side : edge ? Math.sin(angle) * delta : 0;
      const at = { bubbles: true, cancelable: true, dataTransfer: dt, altKey, clientX: toId ? r.left + r.width / 2 + dx : r.left + 5, clientY: toId ? r.top + r.height / 2 + dy : r.top + 5 };
      host.dispatchEvent(new DragEvent('dragover', at));
      const feedback = { hint: host.dataset.dropHint, marker: !!host.querySelector('.insert-marker') };
      host.dispatchEvent(new DragEvent('drop', at)); src.dispatchEvent(new DragEvent('dragend', at)); return feedback;
    }, { fromId, toId, altKey, edge });
    const original = disk();
    const topCircle = await page.locator('#stage [data-id="files"]').boundingBox();
    await page.locator('#stage [data-id="pictures"]').dragTo(page.locator('#stage [data-id="files"]'), { targetPosition: { x: 2, y: topCircle.height / 2 } });
    await saved(page);
    assert.deepEqual(disk().items.map(i => i.id), ['pictures', ...original.items.map(i => i.id).filter(id => id !== 'pictures')], 'Real pointer drop beside a circle inserts before it');
    await page.locator('#undo').click(); await saved(page);
    // Each side inserts instead of exchanging: intervening actions shift intact.
    for (const [target, side] of [['files', 'before'], ['documents', 'after'], ['edit', 'before'], ['pictures', 'after']]) {
      const source = target === 'pictures' ? 'files' : 'pictures';
      const expected = original.items.map(i => i.id).filter(id => id !== source);
      expected.splice(expected.indexOf(target) + (side === 'after' ? 1 : 0), 0, source);
      const feedback = await coordinateDrop(source, target, false, side); await saved(page);
      assert.equal(feedback.marker, true); assert.match(feedback.hint, side === 'before' ? /Colocar antes/ : /Colocar después/);
      assert.deepEqual(disk().items.map(i => i.id), expected);
      assert.deepEqual(disk().library, original.library);
      await page.locator('#undo').click(); await saved(page);
    }
    // Rotated arcs use their own ordering, not the screen's left/right direction.
    await page.locator('[data-page="shape"]').click();
    await page.locator('[data-setting="rotation"]').evaluate(el => { el.value = '90'; el.dispatchEvent(new Event('input', { bubbles: true })); }); await saved(page);
    await page.locator('[data-page="actions"]').click(); await page.locator('.row[data-id="edit"]').click();
    const groupBefore = disk().items.find(i => i.id === 'edit').items.map(i => i.id);
    await coordinateDrop('copy', 'redo', false, 'after'); await saved(page);
    assert.deepEqual(disk().items.find(i => i.id === 'edit').items.map(i => i.id), [...groupBefore.slice(1), 'copy']);
    await page.locator('#undo').click(); await saved(page);
    await page.locator('#undo').click(); await saved(page);
    await coordinateDrop('pictures', 'desktop', false, true); await saved(page);
    assert.equal(disk().items.findIndex(i => i.id === 'pictures'), original.items.findIndex(i => i.id === 'desktop'));
    assert.equal(disk().items.findIndex(i => i.id === 'desktop'), original.items.findIndex(i => i.id === 'pictures'));
    assert.deepEqual(disk().library, original.library);
    await page.locator('#undo').click(); await saved(page);
    await coordinateDrop('pictures', null);
    assert.deepEqual((await page.evaluate(() => window.aptic.state())).config, original, 'Empty preview does not remove anything');
    await coordinateDrop('pictures', 'desktop', true); await saved(page);
    const created = disk().items.find(i => i.type === 'group' && i.items.some(k => k.id === 'pictures'));
    assert.deepEqual(created.items.map(i => i.id), ['desktop', 'pictures']);
    await page.locator('#undo').click(); await saved(page);
    await coordinateDrop('pictures', 'edit'); await saved(page);
    assert.ok(disk().items.find(i => i.id === 'edit').items.some(i => i.id === 'pictures'));
    await page.locator('#undo').click(); await saved(page);
    const drag = (from, to) => page.evaluate(([a, b]) => {
      const src = document.querySelector(a), dst = document.querySelector(b), dt = new DataTransfer();
      const r = dst.getBoundingClientRect(), at = { bubbles: true, cancelable: true, dataTransfer: dt, clientX: r.left + r.width / 2, clientY: r.top + r.height / 2 };
      src.dispatchEvent(new DragEvent('dragstart', at)); dst.dispatchEvent(new DragEvent('dragover', at)); dst.dispatchEvent(new DragEvent('drop', at)); src.dispatchEvent(new DragEvent('dragend', at));
    }, [from, to]);
    await drag('#stage [data-id="downloads"]', '#ring-store'); await saved(page);
    assert.ok(disk().library.some(i => i.id === 'downloads'));
    assert.ok(!disk().items.some(i => i.id === 'downloads'));
    await page.locator('#library-toggle').click();
    await page.locator('#library-search').fill('descargas');
    assert.equal(await page.locator('#library .tile').count(), 1);
    await page.locator('#library .tile').dblclick(); await saved(page);
    assert.ok(disk().items.some(i => i.id === 'downloads'), 'Double click actually inserts library action');
    await page.locator('#library-search').fill('');
    await page.locator('#library-catalog').click(); await page.locator('#library-search').fill('guardar');
    await page.locator('#library .tile').click(); await saved(page);
    assert.ok(disk().items.some(i => i.target === 'CommandOrControl+S'));
    await page.locator('#library-close').click();
    await drag('#stage [data-id="pictures"]', '#stage [data-id="edit"]'); await saved(page);
    assert.ok(disk().items.find(i => i.id === 'edit').items.some(i => i.id === 'pictures'));
    await page.locator('#undo').click(); await saved(page);
    assert.ok(disk().items.some(i => i.id === 'pictures'));
    await page.locator('[data-page="appearance"]').click(); await page.locator('[data-palette="lagoon"]').click(); await saved(page);
    assert.equal(disk().ringAccent, '#4cc0bd'); assert.equal(disk().theme, 'carbon');
    assert.equal(await page.locator('#page-appearance .ring').evaluate(el => getComputedStyle(el).getPropertyValue('--accent').trim()), '#4cc0bd');
    await page.locator('[data-page="shortcut"]').click();
    await page.locator('[data-setting="mouseMode"] [data-value="double"]').click();
    await page.locator('[data-setting="selectionMode"] [data-value="precise"]').click();
    await page.locator('[data-setting="wheelNavigation"]').check(); await saved(page);
    assert.equal(disk().mouseMode, 'double'); assert.equal(disk().selectionMode, 'precise'); assert.equal(disk().wheelNavigation, true);
    // Exercise radial hit testing and dwell lifecycle without executing desktop actions.
    const radial = await page.evaluate(async () => {
      const { mountRadial } = await import('./radial.js');
      const { config } = await window.aptic.state();
      const host = document.createElement('div'); host.style.cssText = 'position:fixed;left:0;top:0;width:600px;height:600px;z-index:100'; document.body.append(host);
      const c = { ...config, nativeIcons: false, animation: 'none', duration: 0, items: config.items.slice(0, 2), selectionMode: 'precise' };
      let choices = 0;
      let api = mountRadial(host, c, { mode: 'live', instant: true, onChoose: () => choices++ });
      const rect = api.root.getBoundingClientRect();
      api.track(rect.left, rect.top - 50); const gap = api.aimedItem;
      api.track(rect.left, rect.top - globalThis.apticGeometry.ring(c).radius); const hit = api.aimedItem?.id;
      api.destroy();
      api = mountRadial(host, { ...c, selectionMode: 'dwell', dwellDelay: 350 }, { mode: 'live', instant: true, onChoose: () => choices++ });
      api.aimAt(0); await new Promise(r => setTimeout(r, 400)); const dwell = choices;
      api.aimAt(1); api.destroy(); await new Promise(r => setTimeout(r, 400));
      const cancelled = choices === dwell;
      api = mountRadial(host, { ...c, selectionMode: 'sector' }, { mode: 'live', instant: true, hold: true, onChoose: () => choices++ });
      const center = api.root.getBoundingClientRect(); api.track(center.left, center.top); api.queueTrack(center.left, center.top - 90); api.release();
      const released = choices === dwell + 1;
      api.destroy(); host.remove(); return { gap, hit, dwell, cancelled, released };
    });
    assert.equal(radial.gap, null); assert.ok(radial.hit); assert.equal(radial.dwell, 1); assert.equal(radial.cancelled, true); assert.equal(radial.released, true);
    await page.locator('[data-page="actions"]').click();
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')).setSize(1080, 700));
    await page.waitForTimeout(500);
    const fits = await page.evaluate(() => ['.studio', '#stage', '#inspector', '#ring-store'].every(s => { const r = document.querySelector(s).getBoundingClientRect(); return r.width > 100 && r.bottom <= innerHeight && r.right <= innerWidth; }));
    assert.equal(fits, true, 'Workspace fits minimum window size');
    await page.screenshot({ path: path.join(root, 'artifacts/studio-compact.png') });
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')).setSize(1440, 900));
    await page.waitForTimeout(500);
    await page.locator('#inspector').evaluate(el => el.scrollTop = 0);
    await page.screenshot({ path: path.join(root, 'artifacts/studio-updated.png') });
    await page.locator('#library-toggle').click(); await page.locator('#library-search').fill('');
    await page.screenshot({ path: path.join(root, 'artifacts/library-updated.png') });
    assert.deepEqual(errors, []);
    console.log('PASS: fixed panels, radial DOM reuse, circle drag, library search/double click/catalog, groups/undo, custom palette, gesture persistence, precise/dwell/release, minimum window layout');
  } finally { await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
